# This file builds and runs the Node server for the agent using Yarn.
# Checks to ensure successful compile, lint, and  run. 
#
# The versioning is locked in the root agent folder. See @yarn.lock file.
#

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install System Dependencies
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y python3 build-essential curl
          fi

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install Dependencies
        run: yarn install
        working-directory: app/agent

      - name: List Installed Node Modules
        run: ls -la node_modules
        working-directory: app/agent

      - name: Run Lint
        run: yarn lint
        working-directory: app/agent

      - name: Run Build
        run: yarn build
        working-directory: app/agent
